import Head from "next/head";
import { Inter } from "next/font/google";
import { auth } from "../firebase/firebaseApp";
import { Box, Text, Heading } from "@chakra-ui/react";
import styles from "@/styles/Index.module.css";

export default function Home() {
  const user = auth.currentUser; // currently signed in user?

  return (
    <>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Heading>Home</Heading>
        {user && <Text>Welcome, {user.email}.</Text>}
      </Box>
    </>
  );
}
