import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Text, Heading } from "@chakra-ui/react";
import styles from "@/styles/Index.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Heading>Home page</Heading>
      </Box>
    </>
  );
}
